<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'name' => 'Fast charging',
                'price' => 1200,
                'quantity' => 100,
                'rating_avg' => 4.5,
                'description' => "Empowering your devices swiftly. Experience rapid recharges, saving time and enhancing productivity on-the-go with our cutting-edge technology. Power up in minutes, not hours.",
                'seller_id' => 1,
                'category_id' => 4,
            ],
            [
                'name' => 'Full Screen Coverage',
                'price' => 750,
                'quantity' => 50,
                'rating_avg' => 4.2,
                'description' => "Immersive visual experience guaranteed. Enjoy edge-to-edge brilliance with our comprehensive display solution, ensuring every pixel counts for maximum engagement and enjoyment.",
                'seller_id' => 1,
                'category_id' => 4,
            ],
            [
                'name' => 'Desk Phone Holder',
                'price' => 450,
                'quantity' => 100,
                'rating_avg' => 3.5,
                'description' => 'Elevate your workspace organization. Securely cradle your device for hands-free convenience, optimizing productivity and accessibility on your desk or workstation with effortless style and stability.',
                'seller_id' => 1,
                'category_id' => 4,
            ],
            [
                'name' => 'POCO M6 Pro',
                'price' => 29000,
                'quantity' => 5,
                'rating_avg' => 4.5,
                'description' => 'Unleash the power of innovation. Experience seamless performance, stunning visuals, and cutting-edge features packed into a sleek design, redefining smartphone excellence for the modern era.',
                'seller_id' => 2,
                'category_id' => 7,
            ],
            [
                'name' => 'Calendar device',
                'price' => 1000,
                'quantity' => 4,
                'rating_avg' => 2.9,
                'description' => "Your indispensable daily companion. Seamlessly manage schedules, appointments, and tasks with intuitive design and connectivity, ensuring efficiency and organization in your daily life.",
                'seller_id' => 1,
                'category_id' => 4,
            ],
            [
                'name' => 'Engraver',
                'price' => 250,
                'quantity' => 160,
                'rating_avg' => 4.5,
                'description' =>"Precision meets artistry. Craft intricate designs with meticulous detail, transforming surfaces into personalized masterpieces. Elevate gifts, awards, and keepsakes with timeless elegance and lasting impressions." ,
                'seller_id' => 3,
                'category_id' => 10,
            ],
            [
                'name' => 'Chairs',
                'price' => 4200,
                'quantity' => 10,
                'rating_avg' => 4.1,
                'description' => " Where comfort meets style. Experience ergonomic support and aesthetic appeal in every design. Elevate your space with our range of chairs, blending functionality with sophistication for ultimate relaxation.",
                'seller_id' => 1,
                'category_id' => 10,
            ],
            [
                'name' => 'TV Screen',
                'price' => 25990,
                'quantity' => 100,
                'rating_avg' => 4.5,
                'description' => " Gateway to entertainment brilliance. Immerse yourself in stunning visuals and vibrant colors, transforming any space into a cinematic experience. Elevate your viewing pleasure with cutting-edge technology and unparalleled clarity.",
                'seller_id' => 1,
                'category_id' => 8,
            ],
            [
                'name' => 'Stuff Printer',
                'price' => 19990,
                'quantity' => 8,
                'rating_avg' => 3.7,
                'description' => " Revolutionizing creation on demand. Print 3D objects with precision and speed, bringing imagination to life. Empower innovation and customization with limitless possibilities at your fingertips.",
                'seller_id' => 1,
                'category_id' => 4,
            ],
            [
                'name' => 'Water Cooler',
                'price' => 23000,
                'quantity' => 5,
                'rating_avg' => 3.2,
                'description' => " Hydration meets convenience. Enjoy crisp, refreshing water at your fingertips, fostering a healthy workplace or home environment. Elevate comfort and productivity with our efficient and stylish cooling solutions.",
                'seller_id' => 2,
                'category_id' => 4,
            ],
            [
                'name' => 'Smart Watch',
                'price' => 1800,
                'quantity' => 100,
                'rating_avg' => 4.9,
                'description' => " Your wearable tech companion. Seamlessly integrate fitness tracking, notifications, and style into your daily routine. Stay connected and motivated with sleek design and intelligent features, enhancing every moment.",
                'seller_id' => 2,
                'category_id' => 4,
            ],
            [
                'name' => "Men's Coats",
                'price' => 4600,
                'quantity' => 80,
                'rating_avg' => 4.2,
                'description' => " Timeless style meets functionality. Embrace warmth and sophistication with our curated collection of coats for men. Elevate your wardrobe with quality craftsmanship and versatile designs for every occasion." ,
                'seller_id' => 3,
                'category_id' => 6,
            ],
            [
                'name' => "Women's Coats",
                'price' => 12000,
                'quantity' => 9,
                'rating_avg' => 4.5,
                'description' =>"Effortless elegance for every season. Discover our curated selection of coats, blending fashion-forward designs with cozy comfort. Elevate your style with timeless pieces crafted to complement any ensemble." ,
                'seller_id' => 3,
                'category_id' => 3,
            ],
            [
                'name' => 'Hand Wallet',
                'price' => 1250,
                'quantity' => 11,
                'rating_avg' => 4.1,
                'description' => " The epitome of style and functionality. Keep your essentials organized and accessible with our sleek hand wallet. Elevate your everyday carry with minimalist design and premium materials for effortless sophistication." ,
                'seller_id' => 3,
                'category_id' => 3,
            ],
            [
                'name' => 'Table',
                'price' => 2300,
                'quantity' => 2,
                'rating_avg' => 4.5,
                'description' =>"The cornerstone of your living experience. From intimate dinners to productive work sessions, our tables provide the perfect setting for every occasion. With timeless design and durable construction, they promise to be both practical and aesthetically pleasing, enhancing the ambiance of any room." ,
                'seller_id' => 4,
                'category_id' => 10,
            ],
            [
                'name' => 'Gas Sensor',
                'price' => 990,
                'quantity' => 10,
                'rating_avg' => 2.8,
                'description' => " Safeguarding your environment with precision. Detect potential hazards and maintain air quality with our advanced gas sensor technology. Reliable and responsive, it provides peace of mind in any setting, from homes to industrial spaces.",
                'seller_id' => 2,
                'category_id' => 4,
            ],
            [
                'name' => 'Stuff Holder',
                'price' => 420,
                'quantity' => 70,
                'rating_avg' => 2.5,
                'description' => " Simplifying organization with style. Keep your essentials tidy and accessible with our versatile holder. Whether for office supplies or personal items, its sleek design and durable construction elevate functionality while adding a touch of elegance to any space.",
                'seller_id' => 4,
                'category_id' => 10,
            ],
            [
                'name' => 'Tree Shears',
                'price' => 220,
                'quantity' => 140,
                'rating_avg' => 3.5,
                'description' => "Precision meets power in arboreal management. Effortlessly shape your landscape with our robust tree shears. Designed for efficiency and ease-of-use, they offer a seamless solution for pruning and maintenance tasks, ensuring your outdoor space thrives with minimal effort.",
                'seller_id' => 4,
                'category_id' => 10,
            ],
            [
                'name' => 'Android Game',
                'price' => 1230,
                'quantity' => 100,
                'rating_avg' => 4.5,
                'description' => "Android Game Dive into immersive entertainment on-the-go. Experience captivating gameplay, stunning graphics, and innovative features designed for Android devices. Whether you're seeking adventure, strategy, or casual fun, our game promises endless excitement and engagement.",
                'seller_id' => 3,
                'category_id' => 1,
            ],
            [
                'name' => 'Smart Tablet Game',
                'price' => 1020,
                'quantity' => 30,
                'rating_avg' => 4.8,
                'description' => "Elevate your gaming experience with cutting-edge technology. Enjoy rich graphics, intuitive controls, and immersive gameplay designed specifically for smart tablets. Discover endless fun and challenge, anytime, anywhere.",
                'seller_id' => 3,
                'category_id' => 1,
            ],
            [
                'name' => 'Car Game',
                'price' => 120,
                'quantity' => 300,
                'rating_avg' => 4.5,
                'description' => "Fuel your need for speed. Experience the thrill of high-octane racing with stunning graphics, realistic physics, and immersive gameplay. Compete, customize, and conquer the tracks in the ultimate driving adventure.",
                'seller_id' => 3,
                'category_id' => 1,
            ],
            [
                'name' => 'Plush Toy',
                'price' => 820,
                'quantity' => 15,
                'rating_avg' => 4.5,
                'description' => "Adorable and huggable companion for all ages. This charming blue plush features an endearing design and irresistibly soft, cuddly texture, perfect for snuggling, playtime, or as a delightful decor piece. Its high-quality craftsmanship ensures durability, making it a beloved friend for years to come. Bring joy, comfort, and a touch of whimsy to your life with this lovable plush toy.",
                'seller_id' => 3,
                'category_id' => 1,
            ],
            [
                'name' => 'Soccer Ball',
                'price' => 4590,
                'quantity' => 10,
                'rating_avg' => 4.4,
                'description' => " Ignite your passion for the game with this vibrant soccer ball. Designed for durability and optimal performance, it features a striking pattern and high-quality materials, perfect for both practice and match play. Elevate your skills and enjoy endless hours of fun on the field with this dynamic and reliable soccer ball.",
                'seller_id' => 4,
                'category_id' => 2,
            ],
            [
                'name' => 'Agility Rings',
                'price' => 790,
                'quantity' => 300,
                'rating_avg' => 3.7,
                'description' =>"Elevate your training with these vibrant agility rings. Perfect for athletes of all levels, they help improve speed, coordination, and footwork. Crafted from durable materials, they withstand intense workouts and are ideal for both indoor and outdoor use. Add versatility to your fitness routine with these colorful and essential training tools." ,
                'seller_id' => 4,
                'category_id' => 2,
            ],
            [
                'name' => 'Weight Lifting',
                'price' => 1120,
                'quantity' => 21,
                'rating_avg' => 4.1,
                'description' => "Transform your strength and physique with weight lifting. This powerful exercise builds muscle, improves endurance, and enhances overall fitness. Whether you're a beginner or an experienced lifter, incorporating weights into your routine promotes bone health, boosts metabolism, and provides a comprehensive workout. Elevate your training and achieve your fitness goals with weight lifting.",
                'seller_id' => 4,
                'category_id' => 2,
            ],
            [
                'name' => 'Work Stuff',
                'price' => 10200,
                'quantity' => 7,
                'rating_avg' => 4.3,
                'description' => "Your essential productivity companion. Simplify tasks, coordinate projects, and foster seamless collaboration. Effortlessly manage your workload and achieve peak efficiency with Work Stuff's comprehensive features.",
                'seller_id' => 4,
                'category_id' => 10,
            ],
            [
                'name' => 'Test Battery Device',
                'price' => 8400,
                'quantity' => 2,
                'rating_avg' => 4.5,
                'description' => "Introducing our Test Battery Device: a versatile tool designed for accurate and efficient testing across various applications. With advanced features and user-friendly interface, it ensures reliable performance in every test scenario.",
                'seller_id' => 2,
                'category_id' => 4,
            ],
            [
                'name' => 'The Tiling Machine',
                'price' => 20000,
                'quantity' => 10,
                'rating_avg' => 4.2,
                'description' => "Revolutionize your tiling process with precision and speed. This innovative device ensures flawless tile placement, optimizing efficiency and quality for every project.",
                'seller_id' => 4,
                'category_id' => 10,
            ],
        ];

        // Insert the products into the database
        foreach ($products as $productData) {
            Product::create($productData);
        }
    }
}
